excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- Source/ExcludedFolder
- Source/ExcludedFile.swift

disabled_rules: # rule identifiers to exclude from running
- line_length
- trailing_whitespace
- vertical_whitespace
- type_name

identifier_name:
    min_length: 2 # only min_length
    excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey


